### ISSUE TITLE
Is there a way to help without getting spoilers?

### ISSUE THREAD

**Issue by 9Morello** [07th-mod/tatarigoroshi#1]
Well, title says it all. I'd love to help the manual process if I can, but is it possible to do so without getting spoilers?

**Comment by ItaloKnox** [comment]
Not at all since you need to read the scripts to manually fix them.

**Comment by 9Morello** [comment]
@ItaloKnox As expected. Anyway, thanks for the good work, looking forward to it.

**Comment by enumag** [comment]
@ItaloKnox I don't mind spoilers (I've seen the anime) - is there a way to help if I don't know japanese?

By the way have you seen Umineko mod anywhere?

**Comment by ItaloKnox** [comment]
Yes and no, usually it's more like comparing a list and seeing if the japanese text matches. [That's how it works](http://i.imgur.com/ySMAgSE.png).

Sometimes the text doesn't fully match, so understanding a little of japanese is always good. But you can work through it just fine just by searching. The voice list will always follow the script, so it's not that hard, just boring.

By the way, Umineko voice and graphics mod will also happen. Game releases in two weeks, work will start right after that.

**Comment by enumag** [comment]
I don't think I'd be able to compare the text quickly enough by eyes withought understanding the symbols... Could part of the process be done automatically by some script?

Good to hear about Umineko. :-)

**Comment by ItaloKnox** [comment]
Yes, most of the process is actually automated. The anon who created the script didn't show up yet, so that's why there's no progress. We have to wait until he shows up or make a new script, since he didn't share his work.
