### ISSUE TITLE
Missing voice file

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#11]
@ItaloKnox I'm going through the second day of Tatari and I noticed [this line](https://github.com/07th-mod/tatarigoroshi/blob/1e36d5b0f93541bdc12f63461b4882c7e9e1dd9f/Update/tata_002.txt#L4121-L4122) doesn't have a voice file. Considering other Satoko's lines near this one the file should be named S19/04/500400395 - but it does not exist in my game files. Could it be somewhere else? I mean there were cases like this in Onikakushi as well (https://github.com/07th-mod/onikakushi/tree/master/SE).

**Comment by ItaloKnox** [comment]
It seems this line is one of these odd cases where some lines are removed from the PS3 version without any clear reason. We can try to find this voice file using the PS2 voices, but I don't remember if they come with the script. The two voice packs are [here](https://mega.nz/#F!SRt1DTKI!0vSWMtBLaa2VO0bDgfzb7A), if you want to try. I can also take a look but not today, my third world internet isn't helping that much.

**Comment by enumag** [comment]
I found it in there, thanks! ;-) I'll send a pull request.
