### ISSUE TITLE
Wrong sprite

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/tatarigoroshi#15]
Should be Rena not Mion.

tata_010
DrawBustshotWithFiltering( 1, "me_se_de_a1", "left", 7, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );

//「...そうだね＠......先生がいろいろと手配してくれたんでしょ＠うん＠...きっと大丈夫だよ。＠
    PlaySE(4, "S03/02/140200122", 128, 64);
    OutputLine(NULL, "「…そうだね。",
           NULL, "\"...Me too.", Line_WaitForInput);

**Comment by ItaloKnox** [comment]
Gotcha, should be fixed now. Can you see if it displays fine? I don't usually mess with sprites, so I don't know if we have to fix the coordinates too.

**Comment by Kamlingen** [comment]
Looks good.

**Comment by ItaloKnox** [comment]
Nice, thanks for reporting this!
