### ISSUE TITLE
tata_jisitu using wrong BG

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/tatarigoroshi#16]
tata_jisitu01-03 was using the wrong BG so I tried making a fix for it :P

https://mega.nz/#!ptoyFbrZ!L0GJuEF1-c0dvxIOe8q1x1I3LzphzRufWQ5NKsZcgeg

**Comment by enumag** [comment]
Oh the difference is that the doors are closed in your patch. Took me some time to see it. :-)

**Comment by ItaloKnox** [comment]
Gotcha, graphics patch updated with the new images. :)
