### ISSUE TITLE
Text / voice inconsistency in chapter 4

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#19]
Here are the lines I'm talking about: https://github.com/07th-mod/tatarigoroshi/blob/master/Update/tata_004.txt#L1310-L1325

In the voice files Keichi actually mispells his name to "Umm... Mr. Iria, was it?" and then the Coach corrects him instead of saying "That's right."

I can fix the english text but I need someone to check if the japanese text is correct and fix it if not.

**Comment by ItaloKnox** [comment]
The "that's right" is definitely wrong here. He says "I'm Irie", or like I would prefer to say, "It's Irie". The japanese lines are correct in this case, 入谷 translate to "Iriya" when Keiichi says it, and then he corrects it later.

Now, the Iriya in this case isn't a Fate pun? Or maybe I'm just stretching things.

**Comment by enumag** [comment]
I'd just write it as Iria. I do like puns but this one seems a bit of a stretch to me.
