### ISSUE TITLE
Missing voice files

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#22]
I was a bit tired with how difficult it is to install Higurashi patches (graphics + voices + this patch + steam sprites patch) so this weekend I finally did what I had in mind for a long time and wrote some scripts to download everything, put it together, remove voices that are not used (meaning I no longer need [symbolic links](https://github.com/07th-mod/guide/wiki/Part-1---Voice-and-Graphics-Patch#saving-hdd-space-with-symbolic-links) to save space), compress all images and fix the character case to avoid problems on linux. While the graphics patch alone for Tatarigoroshi has about 2.7GB my compiled patch with voices and both PS3 and Steam sprites has just slightly over 1GB.

While parsing the script to remove voice files that are not used it also detects voice files that are mentioned in the scripts but not present in the SE directory. Either they're missing or they should not be used in Tatari because they are for some other episode - it is a bug either way. So here is the result from my script:

```
Missing files (13):
S01/11/120700253
S03/00/docA04014
S03/02/140200017
S04/36/310100713
S05/13/101300661
S09/01/170100368
S11/00/VT3B_keijiA2007
S12/10/281000048
S13/00/VT4A_yamaC1022
S14/01/210101319
S14/03/210300615
S16/45/DS43071861
S17/01/110100211
```

As you can see it's mostly references to SXX directories that should not be used by Tatarigoroshi. I'll go over them later after I finish the same scripts for Onikakushi, Watanagashi and Himatsubushi. If someone has time and wants to have a look at these missing files before I get to it, be my guest.

**Comment by ItaloKnox** [comment]
I was getting ready to start working on this but looks like you already managed to fix it, many thanks for that. Just a little longer before we start working on the next chapter, see you there!

**Comment by ItaloKnox** [comment]
Oh, hey, I actually went through checking the commits and forgot about the most important part: any plans on sharing the script? Maybe we can try to put together something fancy and stop having people do complicated steps. I think we're at the perfect point *for development*, but less than the optimal for the regular user. So, what do you think?

**Comment by enumag** [comment]
And here I was afraid you were not interested. Of course I'll share it - wouldn't mention it otherwise. Let me create a new repository for it, add a readme file and then we can discuss any improvements.

**Comment by ItaloKnox** [comment]
Sure! I'm going to bed for now but I hope we can make something cool for the next chapter. When I posted that first comment I did it while checking the pull requests so I forgot about it completely, just remembered that a couple hours ago after updating the wiki for Meakashi.

By the way, is there a way of compiling a list of all voice files used in every chapter? If we're going to make the process easier, then it should be worth to stop using multiple packs for the whole game and start making individual packs for every chapter.

**Comment by enumag** [comment]
For now the script copies all the voice directories needed for the chapter (s03, s19 and s20 for Tatarigoroshi) and then it goes through them and deletes all the unused ones leaving only the needed voices. It will be easy for me to add a way to save the complete list instead of this filtering.
