### ISSUE TITLE
Missing voices

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#28]
There are no voices in [this part](https://github.com/07th-mod/tatarigoroshi/blob/master/Update/tata_008.txt#L1774-L1850). I guess the PS3 text was too different then?

Is there a chance that PS2 would have the correct voices? Recently we had one issue where it was the case.

Otherwise we should probably add it to known issues. (I already added the names there of course.)

**Comment by ItaloKnox** [comment]
If I recall correctly that was censored in the PS3 text. I actually found the first two voices for Keiichi in the PS2 files.

I'll try to find the rest and push it.

**Comment by enumag** [comment]
If some voices are different in PS2 then maybe we should change the text a little? I mean the PS2 text doesn't seem to be censored too much (see #29).

**Comment by ItaloKnox** [comment]
Got everything we needed from the PS2 voices. Thank god we have them and they use the same numbers.

Please check it later, I was doing three things at the same time so maybe I goofed somewhere.
