### ISSUE TITLE
Better images for Tatari ending

### ISSUE THREAD

**Issue by Grelo** [07th-mod/tatarigoroshi#32]
@enumag  
I made better images with text in the center so it is more readable now unlike with previous ones which were covered by the text box and not acceptable because of it. Please overwrite the old ones in graphic mod, thanks :)

https://mega.nz/#!hIEhWJyJ!VfTzJnokdm9IQlrBgYzjIYbUDS_lT13LIw89-WKlKbM

**Comment by ItaloKnox** [comment]
Had some downtime issues due to Github's buggy API but the update should now be included in the latest graphics patch. 👍

**Comment by P-Chang** [comment]
I already fixed it.
It works both mode and  both language.
https://github.com/07th-mod/tatarigoroshi/pull/30

Example( top right is deleted in master ):
http://www.dailymotion.com/video/x5upmtt

**Comment by enumag** [comment]
@Grelo Great work! 👍
