### ISSUE TITLE
Missing Alt+F4 dialog

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#36]
When you try to close Higurashi game using Alt+F4 the game first shows a Yes/No dialogue to confirm.

This works fine in all other chapters but in Tatarigoroshi the dialog is not shown.

@P-Chang Could you see if you have the same issue with your own Tatarigoroshi installation? It might be just something on my end. If you have the same issue, could you look into it?

**Comment by P-Chang** [comment]
You probably just disable "Display Confirmation Boxes" accidentally.
I met same issue in few weeks ago.

**Comment by enumag** [comment]
lol you're right of course... I completely forgot the game even had that feature

Still though with confirmation boxes disabled I'd expect the game to close on Alt+F4.

**Comment by P-Chang** [comment]
In that night, I thought I made bug, and I looked over all edited method.
It was really ridiculous night :joy:
