### ISSUE TITLE
WaitForVoice bug?

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#38]
@P-Chang As per your advice I added WaitForVoice here: https://github.com/07th-mod/tatarigoroshi/commit/7b699e5a347d40473cf9dd8b3fb88cdc4b3e7c3b

The thing is it does not work - the game just freezes there. Here is my hypotheses of what happened:

I think it is because the voice is relatively short and my text speed is fast so the voice actually finished before the command is reached. So then it tries to wait for the channel but there is no voice currently playing so it is just waiting for [Godot](https://en.wikipedia.org/wiki/Waiting_for_Godot).

If I'm right, can you update WaitForVoice to not do anything if there is no voice currently plaing in that channel?

If I'm wrong is it a bug in the DLL or did I call it incorrectly?

**Comment by P-Chang** [comment]
Totally sorry, true command name is "WaitToFinishVoicePlaying".
I'm confused in differences between command name and method name in dll.

**Comment by enumag** [comment]
That works, thank you!
