### ISSUE TITLE
Missing voice

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#39]
We have a missing voice here: https://github.com/07th-mod/tatarigoroshi/blob/master/Update/tata_010_03.txt#L354-L360

Based on the voice numbers I think these two voices belong there but they probably have some different meaning?

https://www.dropbox.com/s/zlbaneez8247jum/142700008.ogg?dl=0
https://www.dropbox.com/s/fne0jon5kdq72sc/142700009.ogg?dl=0

Here is the relevant part from PS3 script:

```
圭一の母rvS03/00/142700008.「そうねぇ……よくできた推理小説……う～ん……」
圭一の母rvS03/00/142700009.「結構どれもこれも色んな魅力があって、どれが面白かったとは言いにくいけど、強いてあげれば……」
```

I think it's not exactly censorship, looks like they just removed references to real-world novels.

@P-Chang Can we have a fork here just like earlier with Tomitake?

**Comment by P-Chang** [comment]
OK, I'll make it.

How we treat English dialog?
Scenes don't have big differences, but dialog are completely different.

1.Replace to Japnese dialog.
It is common in community translation. Translator will be able to realize it in gaming.
But almost English user will confuse.

2.Add comment in script file.
If we have rule of comment, translator can search with grep and find it easily.

In this case, we can use both, but some scene have lack of 1 or 2 dialogs.

**Comment by enumag** [comment]
I'm not sure I understand what you mean. Are you talking about dealing with the fact that we don't have english translation at the moment? I'm sure @ItaloKnox or @DoctorDiablo can translate it for us.

**Comment by P-Chang** [comment]
Sure. I think they can translate it too.

But if I separate these first and add comment it like

```
void dialog001()
{
	PlayVoice(4, "s03/00/142700008", 128);
// NeedTranslate
	OutputLine(NULL, "「そうねぇ……よくできた推理小説……う～ん……",
		   NULL, "\"Of course, Agatha Christie's 'And Then There Were None' is my top recommendation.", Line_WaitForInput);
	PlayVoice(4, "s03/00/142700009", 128);
// NeedTranslate
	OutputLine(NULL, "結構どれもこれも色んな魅力があって、どれが面白かったとは言いにくいけど、強いてあげれば……」",
		   NULL, " And 'Murder on the Orient Express' used some great, bold tricks too, of course. I didn't see it coming at all.\"", GetGlobalFlag(GLinemodeSp));
}
```

They can translate it when they have a lot of time.

I suggested case 1 why CS dialogs sometimes have completely different dialog flow.
In that case, English dialog flow will be completely broken without translation.

**Comment by enumag** [comment]
Use whatever you prefer, we can deal with it either way. Personally I usually use this since it has the advantages of both of your suggestions.

```
	PlayVoice(4, "s03/00/142700008", 128);
	OutputLine(NULL, "「そうねぇ……よくできた推理小説……う～ん……",
		   NULL, "<missing translation>", Line_WaitForInput);
```

**Comment by P-Chang** [comment]
Hmm, It should be used in scene that have different dialog flow.
There are many dialogs that completely different text but translation is not must.

I use comment like `// <missing transration>` for integrity.

**Comment by P-Chang** [comment]
And I finish it.
https://github.com/07th-mod/tatarigoroshi/commit/3c0704b73bd934abdc2a7c36ae56b547d778ff07

**Comment by enumag** [comment]
Thanks!

The branch with original text should not have voices in my opinion. Plus the name line should be inside the branches maybe?

Also what is the empty file ztata_00x_vm0x_n01.txt for?

**Comment by P-Chang** [comment]
In personal judgment, if the voice is not strange for the scene, I put a voice.
I have no objection to you cut it off, but I personally would like to continue this way.

I excluded name lines for keeping the difference to a minimum, but if this way is not good for your work I will include the name line.

**Comment by enumag** [comment]
Alright, keep the voices then.

The name, voice and text should always stay together in my opinion. If you had more than one line then you would have names inside these functions anyway - let's keep it consistent.

**Comment by P-Chang** [comment]
Oh... I should discussed rule with you...

in my old edit

```
name
voice
dialogs
voice
differentdialogs
dialogs
linebreak
drawbustshot
```

to


```
name
voice
dialogs
GCensor branch
dialogs
linebreak
drawbustshot
```

is it should be ?

```
GCensor branch

drawbustshot
```

[edit]
> If you had more than one line

I completely missed this one.

**Comment by enumag** [comment]
In my opinion yes but it is not too important. Have it your way if you want to.

**Comment by P-Chang** [comment]
OK, I'll do it base on your opinion after this.

I worried about redo wata.

**Comment by enumag** [comment]
You didn't answer my question about the ztata_00x_vm0x_n01.txt file - it contains just 2 empty functions. Why is that there?

**Comment by enumag** [comment]
And maybe I should explain why I prefer to have names and line breaks included in the GCensor branch files. It is because I have a lot of scripts by now fixing common mistakes. And sometimes the conditions are based on the whole dialogue - from name to line break. Having just the line itself separately could break some of these scripts.

**Comment by P-Chang** [comment]
it's just blank file for making new branch script file.

**Comment by enumag** [comment]
Also, can I ask you to configure your IDE or whatever editor you're using?

1) Editor should remove trailing whitespaces.
2) Editor should always add a line break to the end of the file.

My script can fix that of course (https://github.com/07th-mod/watanagashi/commit/4c2f119e1b8644a8ec24fcc4438f97181d947dc8) but it makes it difficult to see the changes I'm interested in.

**Comment by P-Chang** [comment]
Sure.

**Comment by enumag** [comment]
@P-Chang Ok, I think that's everything I wanted to ask you here. I'll finish this issue with the others.

@ItaloKnox @DoctorDiablo Everything else is done. Can I ask one of you for translation of the two lines in the first post? No hurry, do it whenever convenient for you. ;-)

Thanks to all of you!

**Comment by ItaloKnox** [comment]
The second sentence is giving me a little trouble. I think I can translate it but I don't think it's going to be good enough. Perhaps @DoctorDiablo can translate this one better than me. I'll do something about it in case he can't do it.

**Comment by DoctorDiablo** [comment]
Here's my attempt at a translation:

> Of course... well done mystery novels... yeah...

> They all have a unique charm to them so it's hard to say which is the most interesting, you'd really have to force me to pick one.

But personally, in this sort of situation I think I'd prefer to keep the original text and play the audio as-is.  The moderate censorship seems a little more annoying than the text not perfectly matching the audio.

**Comment by enumag** [comment]
Yeah that's actually what @P-Chang with the fork - one branch of the fork has what you just said and I thought to put the translation to the other. I can revert the fork if you guys prefer to always use the non-matching text.

@ItaloKnox I think I'll let you decide since I don't mind either way. (It's probably better to keep the fork since we already have it.)

**Comment by ItaloKnox** [comment]
I don't think this one hurts the story, so it shouldn't really be an issue to change it. Honestly, I have nothing against it.

**Comment by enumag** [comment]
Fork it is then. I'll finish it when I have some time. Thanks guys!
