### ISSUE TITLE
Suggestion: add to the readme that this mod adds the CG scenes

### ISSUE THREAD

**Issue by 9Morello** [07th-mod/tatarigoroshi#4]
The Steam version doesn't use CG at any scenes, but the patches available here add them. I've searched a bit and your releases seem to be the firsts that add the CG to a PC version. I think it would be nice to point this in the readme file.

**Comment by ItaloKnox** [comment]
Yeah, actually this is not noted yet because the patch still doesn't support CGs (since they require coding directly into the script). We're working on that already, so when it's ready we'll update everything.
