### ISSUE TITLE
Tata tips 02 PS3 matching

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#43]
I found a minor change in tata tips 02. It doesn't seem to be censorship, just a regular improvement.

Here is the relevant part of PS3 script:

```
圭一rvS20/01/440100118.「ぎゃーーーーー！！！」

r頭を抱えて悶絶する俺と得意絶頂の沙都子！

r甲高い笑い声が教室にこだまする。

rその時、沙都子の頭に、ボフ！っと石灰の粉がかけられた。

r見ると、真っ白けの富田くんと岡村くんが両手いっぱいに石灰の粉を盛って、沙都子に復讐に来ていた。

沙都子rvS20/04/440400071.「わぷっ？！kvS20/04/440400072.　い、いきなり何をなさいますのですか、お二人ともっ？！」

圭一rvS20/01/440100119.「…………どうやら、だれが罠をしかけたのかは問答無用、ってところだな」

沙都子rvS20/04/440400073.「失礼でございますわね！！　どこに証拠がございますの？」
```

In our version voices 440100118 and 440400073 (first and last line) are used but the voices in between are not.

@P-Chang What do you think? Should we make a fork using the changed lines?

**Comment by P-Chang** [comment]
I think it is not important lines too, but fork could be make easily, I'll make it in few days.

**Comment by enumag** [comment]
ping @P-Chang

**Comment by P-Chang** [comment]
https://github.com/07th-mod/tatarigoroshi/commit/3920a275affb2e9d4a2268fb03917575a0d5ca5c

Sorry for late. finished it.

**Comment by enumag** [comment]
Hmm we'll need a sa_se_hn_b2.png for CGAlt as well. What chapter did you take the image from?

**Comment by P-Chang** [comment]
from chapter2 and I put it.
https://github.com/07th-mod/tatarigoroshi/commit/298b1fd51630885ad9a2f50c13a15214966a72b8

**Comment by enumag** [comment]
Thank you!

Note: Voice filed added, only translations are missing.
