### ISSUE TITLE
Translation needed

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#44]
There was an error in the script that one of Keiichi's lines were added to Satoko instead. When I split it the current translation doesn't make much sense so I need a better one.

```
「………今、警察が話してるのを聞いてた限りじゃ、………。」
```

**Comment by ItaloKnox** [comment]
Can you give me the unsplit translation? I think I need some context.

**Comment by enumag** [comment]
It goes like this:

```
………今、警察が話してるのを聞いてた限りじゃ、………。
……監督が、自殺したらしい。
```

Current translation (written as if both lines were one long sentence said by Keiichi}:

```
...From... what I just heard the police talking about...
...Coach... apparently committed suicide.
```

In reality the first line is said by Satoko and the second by Keiichi. The second can probably stay as is but the first doesn't make much sense on it's own.

If you need further context then look [here](https://github.com/07th-mod/tatarigoroshi/blob/master/Update/tata_013_02.txt#L792-L802).

**Comment by ItaloKnox** [comment]
Well... the translation is correct. It really looks like he says both, and splitting them is quite difficult in this case. The japanese actually gives margin to what is coming next, so the sentence does not make sense by itself.

I guess we just need to adapt it? Perhaps changing the ending a little to make it look like the "talking about" was interrupted?

**Comment by P-Chang** [comment]
probably, it is not need retranslate. 

just changing `...From... what I just heard the police talking about...` to dialog that Satoko tone is enough or it is not needed.

Or making
`...Anyway... what on earth... is going on?  ...From... what I just heard the police talking about...`
to one dialog on your English knowledge is enough.

**Comment by enumag** [comment]
I'll just keep it as is then.
