### ISSUE TITLE
Omake - missing translation

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#45]
@ItaloKnox Nothing major this time. Just one line by Shion announcing that she's the protagonist of Meakashi. It does not need to be exact.

```
詩音rvS20/06/440600118.「大したことじゃないです。kvS20/06/440600119_1.すでにご存じの方もおられるかと思いますけど、kvS20/06/440600120.閲覧できる資料に新しいものが追加されて、……私、園崎詩音のシナリオがプレイできるようになるってことですよ」
```

**Comment by enumag** [comment]
@ItaloKnox Oh and could you translate this as well for me? It's Keiichi being happy about finally getting his own sprite in Meakashi.

```
へっへ～ん、俺の苦労を少しは思い知れ～！！
```

Note for myself: s20/01/440100219

**Comment by ItaloKnox** [comment]
``「大したことじゃないです。``
> That's not a big deal.

``すでにご存じの方もおられるかと思いますけど、``
> As you probably already know,

``閲覧できる資料に新しいものが追加されて、……私、園崎詩音のシナリオがプレイできるようになるってことですよ」``
> some new files to read have been added, and me, Sonozaki Shion, am ready to experience my own scenario.

Now for Keiichi:
``へっへ～ん、俺の苦労を少しは思い知れ～！！``
> Ahem, at least try to understand my suffering a little!!

**Comment by ItaloKnox** [comment]
Brush it up a little for me, especially the last part for Shion. Didn't make much sense, honestly.

**Comment by enumag** [comment]
@ItaloKnox Something like this then?

```
As you probably already know, a brand new chapter is being added. And I, Sonozaki Shion, will be the main character.
```

I mean this would make sense in this context and we don't have to be exact. In the omake there are plenty of places where even I can tell the translation is far from exact.

**Comment by ItaloKnox** [comment]
Oh, yeah, that makes much more sense. I was quite lost when translating it because it really means what I said but can be used in your context.

**Comment by enumag** [comment]
All done. Thanks!

@P-Chang You might want to make a fork out of this [commit](https://github.com/07th-mod/tatarigoroshi/commit/bd6ea2c173072bb050d3949f864b0dfc0d781cd1). If not, just close this issue.

**Comment by P-Chang** [comment]
Probably I'll make it in later. but I can make branch with commit diff. so I'm fine with closing this.

**Comment by enumag** [comment]
I'll keep it open as a reminder that it's not entirely finished.

**Comment by enumag** [comment]
@P-Chang I'd like to release new version of Tatari. Do you want to make the fork before the release?

**Comment by P-Chang** [comment]
@enumag 
Sorry for late.
https://github.com/07th-mod/tatarigoroshi/commit/ad711268cee56bc2dc521a28761dd83c47983f5d

**Comment by enumag** [comment]
@P-Chang Thank you!
