### ISSUE TITLE
Wrapping up Tatarigoroshi

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#47]
I'm finally done with reading and fixing Tatarigoroshi. The amount of fixes I have done in total was much much bigger than in any other chapter, easily more than a thousand. It's officially the most polished chapter so far. So, dear Tatarigoroshi, you were a huge pain in my ass for a looong time and I'm glad to finally get rid of you.

There are still a few issues to be resolved which I can't solve by myself. When these are fixed we can make a new (and pretty much final) release of Tatarigoroshi.

After that I'm not really sure. I might start with Meakashi since I didn't read that one yet. Or maybe I'll just take a break from Higurashi for a while. It might be the better thing to do after spending so much time on Tata. Either way I'll be back when Tsumihoroboshi is out or Kageboshi translation is finished - whichever comes first.

----

Out of curiosity, there was a line in Tatarigoroshi that confused me. I always thought that "higurashi" are "cicadas", but then in Tata there was a line suggesting otherwise. Can someone explain it to me?

````
...When I thought back, it seemed like birds always chirped in the morning, cicadas always cried loudly in the afternoon, and higurashi always rose up in chorus in the evening—always something to hear.

(japanese)
…こうして思い返すと、朝は小鳥がさえずり、昼はセミが賑やかに鳴き、夕暮れにはひぐらしが合唱する雛見沢のなんとにぎやかだったことか。
```

**Comment by P-Chang** [comment]
Thank you for your hard work.

> Out of curiosity, there was a line in Tatarigoroshi that confused me. I always thought that "higurashi" are "cicadas", but then in Tata there was a line suggesting otherwise. Can someone explain it to me?

https://en.wikipedia.org/wiki/Tanna_japonensis

Isys11.org is higurashi
Isys12.org is cicadas

I don't have knowledge enough.

Japanese Rena `かな？かな？` dialogs are motif of higurashi cicadas.

**Comment by enumag** [comment]
Oh... So basically they are two different bugs with different names in japanese but both are called just cicadas in english?

**Comment by P-Chang** [comment]
Probably yes.
Wikipedia say these live in only Asia.

**Comment by jwgrlrrajn** [comment]
I think I heard that higurashi are "evening cicadas." I guess the cicadas in the earlier context are "afternoon cicadas" or something. I know that higurashi have a rather unique chirping sound, as opposed to most cicadas which have more of a buzzing sound.

**Comment by ItaloKnox** [comment]
@jwgrlrrajn pretty much nailed it. There are two types of cicadas.

**Comment by enumag** [comment]
Thanks for the explanation everyone! :-)

-----

I'm sorry it took me a whole month to get back to Tatarigoroshi and finish it. Finally it's done aside from some missing translations and missing fork (see the other issues for details). Once these are fixed we can make a new release.

Also while fixing this I found out that we had a left-over windo_filter.png in all chapters which caused the NVL mode to not work correctly. I fixed this but we'll need new minor releases for all chapters.

**Comment by P-Chang** [comment]
Probably It only happen in repository. I remember chapter CG archive have all windo_filter.

**Comment by enumag** [comment]
Exactly, they were still in the repos. Archives are fine.

**Comment by ItaloKnox** [comment]
@enumag I'm confused. We have a windo_filter for all chapters in their ``Chapter-CG.zip``, but they are overwritten right after that by the textboxes (which also contains a windo_filter and two others). The repo releases, as far as I know, don't have that because I don't release the master, but select folders instead.

Can you explain why we need minor releases for all chapters?

**Comment by enumag** [comment]
@ItaloKnox You're right. I didn't know that you only copied specific directories for the release. So we just need a new Tata release. Sorry for the confusion.

**Comment by enumag** [comment]
Fun fact: after alll those little fixes I have 230 commits in Tatarigoroshi. That's easily more than I have in all other chapters combined. 😄

**Comment by ItaloKnox** [comment]
To be honest, Tatari was the worst chapter overall to work on. So much stuff changed and god, the scripts were big.

**Comment by enumag** [comment]
Yep. Way too many PS3-related changes. I still remember those >200 voices you had to pull from PS2. That was insane. I'm really glad we're finally done here.

I hope something like that won't occur in the answer arcs. But the scripts will most likely be even bigger since answer arcs are generally longer.

**Comment by enumag** [comment]
Still Tata was fun to read for me since I completely forgot how it ends. I didn't expect to see a GHD here.
