### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by enumag** [07th-mod/tatarigoroshi#49]
@ItaloKnox We have some missing translations in these two commits. Could you look into it?

https://github.com/07th-mod/tatarigoroshi/commit/3920a275affb2e9d4a2268fb03917575a0d5ca5c
https://github.com/07th-mod/tatarigoroshi/commit/5700215432ddda47bcc82852b8404ec587417372

This will fix #40 and #43.

**Comment by ItaloKnox** [comment]
I pushed almost every translation. I'm missing the last two of the first one.
Haven't done that in a while so I'm kinda rusty. If someone takes over I'm ok with it but if no one does, I'll come back to it tonight or tomorrow. Long sentences always give me trouble.

**Comment by ItaloKnox** [comment]
Oh, ok, I really fixed it this time. The last two were really confusing but I brainstormed with a friend who's taking N1 and it worked out. Check that out for me before closing here. 👍

**Comment by enumag** [comment]
I made a little change [here](https://github.com/07th-mod/tatarigoroshi/commit/4b45bd37233bf0785a98bc20f951d498c0f3d3fc) (is it ok?), otherwise it's fine in my opinion.

Thank you!

**Comment by ItaloKnox** [comment]
Yeah, I guess going between english, japanese and portuguese doesn't always work too well. 😆
