### ISSUE TITLE
The game didnt started after installed the patch 

### ISSUE THREAD

**Issue by gagantous** [07th-mod/tatarigoroshi#50]
I have installed the patched using installer patch for windows, then i copied the patch from release page to the game and replace it, but the game didnt started correctly. It just give me a windows scree of the game but the main menu didnt appear, just blank

I am using windows 7

**Comment by ItaloKnox** [comment]
After using the installer, go into the ``temp`` folder that was created inside the game folder, delete the file ``local.txt`` and run the file ``updater.bat``. That should fix the issue.

**Comment by gagantous** [comment]
Thanks, it works (y)
