### ISSUE TITLE
The text didnt appear but the music still played in the background

### ISSUE THREAD

**Issue by gagantous** [07th-mod/tatarigoroshi#51]
There is no text in this scene, but the bgm still playing
![51](https://user-images.githubusercontent.com/24579576/34459417-db58dab2-ee2a-11e7-99b3-4919669dbfeb.png)

This is last scene just after the text disappear
![1235](https://user-images.githubusercontent.com/24579576/34459421-e69cfdb8-ee2a-11e7-964d-c2d812afd709.png)

**Comment by P-Chang** [comment]
Your CG folder have `me_se_fu_b2.png`  `left.png` ?

**Comment by gagantous** [comment]
I have `left.png` but i dont have  `me_se_fu_b2.png` only `me_se_fu_b1.png` @P-Chang

**Comment by ItaloKnox** [comment]
I checked the patch and the file is definitely there. I think your download dropped somewhere and skipped a few files.

I suggest downloading [Tatarigoroshi-CG.zip](https://github.com/07th-mod/resources/releases/download/Nipah/Tatarigoroshi-CG.zip) and replacing your ``CG`` folder with the one that comes with this.

**Comment by gagantous** [comment]
Okay, thanks @ItaloKnox

**Comment by gagantous** [comment]
could someone upload the `me_se_fu_b2.png` only ? it took 4 hour for me to donload that 500mb CG set...
my download speed is not stable now, sometimes it went 20kb or 50kb...

**Comment by enumag** [comment]
![me_se_fu_b2](https://user-images.githubusercontent.com/539462/34460095-de7acf32-ee04-11e7-8025-c09cbc84a481.png)
![me_se_fu_b2](https://user-images.githubusercontent.com/539462/34460096-e5256fb8-ee04-11e7-999b-deccb8d59e54.png)

**Comment by gagantous** [comment]
Thanks @enumag for the CG, it works now !
