### ISSUE TITLE
Satoko Sprite Modification

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/tatarigoroshi#52]
I recall when this chapter was first announced, quite a few fans took issue with one of Satoko's sprites. I'm not going to post it here, because I think the artist was a little excessive with this one. You can look it up in the CGAlt folder.

Anyway, after some time of painstaking editing, I've finally come up with a modification that I'm reasonably happy with. Satotko's revamped towel sprite.
![sa_to_ak_a1](https://user-images.githubusercontent.com/13456824/35958347-ed583894-0c65-11e8-9008-a1665b864723.png)

**Comment by enumag** [comment]
It looked good until I clicked on it to see it fullscreen. The edges and folds you added are considerably more pixelated than the others. I like where this is going though.

**Comment by jwgrlrrajn** [comment]
Gotcha. I think I know of a relatively easy way to fix that now. I'll work on it some more tonight.

**Comment by jwgrlrrajn** [comment]
Here we go. This should do it. ![sa_to_ak_a1](https://user-images.githubusercontent.com/13456824/36012000-d8578150-0d20-11e8-9734-8de252ab0b5f.png)

**Comment by enumag** [comment]
It's not much better to be honest. I still see the pixelation to lesser extent + your edges are now thicker/darker than original ones. When I'm not zoomed in the first attempt actually looks better.

**Comment by jwgrlrrajn** [comment]
Just so I'm clear on this, we're talking about the brown outlines, yes?

**Comment by enumag** [comment]
I see them as black rather than brown but yeah we probably mean the same thing. Just to clarify I highlighted them.

![satoko](https://user-images.githubusercontent.com/539462/36014842-1260d2de-0d6c-11e8-9565-5259983951b7.png)

**Comment by jwgrlrrajn** [comment]
That's a tremendous help. Hopefully, I can get this wrapped up tomorrow.

**Comment by jwgrlrrajn** [comment]
Third time's the charm, I hope. ![sa_to_ak_a1](https://user-images.githubusercontent.com/13456824/36059126-20fb74f8-0df7-11e8-892b-271eadde13db.png)

**Comment by enumag** [comment]
👍 Looks good to me now. :-)

@irlPM @Grelo @ItaloKnox What do you guys think?

**Comment by ItaloKnox** [comment]
I would be a bit more perfectionist but I think it's just nitpicking at this point. It looks good, you can barely notice it's edited.

**Comment by irlPM** [comment]
Yea, I agree with Ítalo. It looks good.

**Comment by jwgrlrrajn** [comment]
Awesome. We'll include these with the next update then.
