### ISSUE TITLE
My game stops at the last tip

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/tatarigoroshi#54]
Hi, am reading tatarigoroshi with the latest patch, am about to finish but while reading the last tip research notes, the game suddenly stops and I can’t do anything.
![sin titulo](https://user-images.githubusercontent.com/28794338/36068262-52daeb4a-0ed1-11e8-845a-c79845179c85.png)

The screen stays like this even if i return to the main menu, hope you can help me to fix this and sorry if I bother you guys uwu

**Comment by ItaloKnox** [comment]
Hi, can you post the ``output_log.txt``?

**Comment by yagamisempai** [comment]
[output_log.txt](https://github.com/07th-mod/tatarigoroshi/files/1713950/output_log.txt)

**Comment by yagamisempai** [comment]
all works fine, only when am reading the tip is when the game stops

**Comment by ItaloKnox** [comment]
I don't see anything strange with the log. When did you install the patch and how did you install it (manual or installer)?

**Comment by yagamisempai** [comment]
manual but i used the ps3 sprites i already have. 
can that be the problem?

**Comment by ItaloKnox** [comment]
I don't understand, you copied the sprites from another chapter and put it in your game?

**Comment by yagamisempai** [comment]
[example.zip](https://github.com/07th-mod/tatarigoroshi/files/1713961/example.zip)
no sorry i do use the sprites of tatari goroshi  here is a example of wat happen

**Comment by ItaloKnox** [comment]
I checked our scripts and still haven't found anything to make the game crash at this part. I'm going to tag @enumag so he can take a better look at this. I don't have the game with the patch applied right now to test it.

**Comment by yagamisempai** [comment]
thank you very much nwn

**Comment by enumag** [comment]
Actually P-Chang already fixed it. https://github.com/07th-mod/tatarigoroshi/commit/b9e7f0ae9892beaddf62f93729501e08125fbb56
