### ISSUE TITLE
Last line in tips not waiting for user input

### ISSUE THREAD

**Issue by Norgus** [07th-mod/tatarigoroshi#59]
https://github.com/07th-mod/tatarigoroshi/blob/fad3be410c0d35dbdd0f56fd633cb65753151745/Update/tata_tips_10.txt#L138-L140

The tips close the moment the last line of text displays, so it cannot be read.
I experimented a little, but wasn't sure how to fix this properly.

The equivalent text in pre-mod script is:
```
	OutputLine(NULL, "＜法務・厚生大臣署名＞",
		   NULL, "<Authored by the Minister of Health and Welfare>", Line_ContinueAfterTyping);
	OutputLineAll(NULL, "\n", Line_ContinueAfterTyping);

	FadeOutBGM( 2, 10, TRUE );
	SetValidityOfInput( FALSE );
	Wait( 2000 );
	SetValidityOfInput( TRUE );
	PlayBGM( 2, "lsys24", 128, 0 );

//!s0　　　　　　　　　　　　!s50第二条・第三条より/
	OutputLine(NULL, "　　　　　　",
		   NULL, "", Line_ContinueAfterTyping);

	FadeOutBGM( 2, 10, TRUE );
	OutputLineAll(NULL, "", Line_WaitForInput);
```

**Comment by enumag** [comment]
@Norgus This should fix the problem: https://github.com/07th-mod/tatarigoroshi/commit/0a10d3640277f4256171c248dc89614b3844a665
