### ISSUE TITLE
Stuck on All-Cast Review Session

### ISSUE THREAD

**Issue by jerome0810** [07th-mod/tatarigoroshi#6]
The game is stuck on the scene with everyone laughing on Tomitake. After hearing them laugh, I could no longer proceed with the game. After deleting the scripts and verifying the game files, I was able to proceed and finish the whole game.

Here is a link of where it stops
http://steamcommunity.com/sharedfiles/filedetails/?id=726251776

EDIT:
I tried editing the script and deleting this part
        PlaySE(5, "S20/03/440300363", 128, 64);
    PlaySE(6, "S20/04/440400213", 128, 64);
    PlaySE(7, "S20/05/440500130", 128, 64);
    PlaySE(8, "S20/08/440800128", 128, 64);
    PlaySE(9, "S20/09/440900125", 128, 64);
    PlaySE(10, "S20/06/440600132_01", 128, 64);
    PlaySE(1, "S20/11/440700400_01", 128, 64);
so it prevented playing the other SE and was able to proceed. Only Mion's laugh was played I think.

Now I got to some later part and the game stopped again on this part.

//「「「乾杯～～～！！！！」」＠
    PlaySE(4, "S20/03/440300368", 128, 64);
    PlaySE(5, "S20/04/440400218", 128, 64);
    PlaySE(6, "S20/05/440500133", 128, 64);
    PlaySE(7, "S20/09/440900128", 128, 64);
    PlaySE(8, "S20/08/440800131", 128, 64);
    PlaySE(9, "S20/06/440600104", 128, 64);
    PlaySE(10, "S20/10/441000080", 128, 64);
    PlaySE(11, "S20/22/441400031", 128, 64);
    PlaySE(12, "S20/11/440700402_01", 128, 64);
    OutputLine(NULL, "「「「乾杯〜〜〜！！！！」」」",
           NULL, "\"\"\"Cheers~~~!!!!\"\"\"", Line_WaitForInput);
    OutputLineAll(NULL, "\n\n", Line_ContinueAfterTyping);

I can't confirm if it is about the number PlaySE supported. But I tried removing some and it stops when there are more than 6 simultaneous voices.

**Comment by ItaloKnox** [comment]
Thanks for the report. Looks like we hit the sound limit, so that's why it stops working.

Can you try to load your save using this file? If it doesn't work there is an easy way of pushing a new update.
[omake_03.txt](https://github.com/07th-mod/tatarigoroshi/files/367903/omake_03.txt)

**Comment by jerome0810** [comment]
I tried using the file and it did work. Thanks for the update!

**Comment by ItaloKnox** [comment]
That's great! Thanks for letting me know, I'll push a new update but you do not need to update yours since you are already using the new file. 👍
