### ISSUE TITLE
Typo in config menu

### ISSUE THREAD

**Issue by orian34** [07th-mod/tatarigoroshi#60]
I just noticed there was a typo in all config menus( I checked Oni and Wata, they have it as well. And I don't know how I managed to miss it...).
![image](https://user-images.githubusercontent.com/12663654/40892353-47648050-6796-11e8-9f1e-e75dd96f08cc.png)

I'm pretty sure the double I is not intentional

**Comment by irlPM** [comment]
I'll be fixing it, thank you for saying it.

**Comment by enumag** [comment]
@irlPM There are other issues in the assets which we need to fix (like the swapped arrows). I already have some WIP versions on my PC. Still I need you or Inochi to send me fixed PNG for the config screen.

**Comment by enumag** [comment]
@irlPM Never mind, I just got it from Inochi.

**Comment by enumag** [comment]
Actually I guess you'll need it as well for Hima UI so here it is:

https://cdn.discordapp.com/attachments/410346263167500300/453266853007982603/configbg_1EN.png

**Comment by enumag** [comment]
Fixed.
