### ISSUE TITLE
CG text typos

### ISSUE THREAD

**Issue by orian34** [07th-mod/tatarigoroshi#61]
Some typos from the CG pictures.
from tips/tata004.png
![image](https://user-images.githubusercontent.com/12663654/41124391-1cdcb7bc-6aa2-11e8-8faa-783fba90737c.png)
Slaking is a pokemon.
![image](https://user-images.githubusercontent.com/12663654/41125026-eeaa9de4-6aa3-11e8-9b4d-09f346b81f35.png)
Just as a reminder, you already know it's on all chapters.

**Comment by enumag** [comment]
Slaking is fixed now.

**Comment by enumag** [comment]
Here are the 4 images effected by the "gyu" typo down under Bern's name. It is supposed to be "guy".

![si_onikakusi](https://user-images.githubusercontent.com/539462/47264452-f66b6e80-d517-11e8-94ac-6f6370e8f3ee.png)
![si_watanagasi](https://user-images.githubusercontent.com/539462/47264460-0a16d500-d518-11e8-84ac-d74f683ed066.png)
![si_tatarigorosi](https://user-images.githubusercontent.com/539462/47264462-113de300-d518-11e8-893e-46a8670cef1b.png)
![si_himatsubusi](https://user-images.githubusercontent.com/539462/47264466-1d29a500-d518-11e8-9586-a8dc301e8241.png)

**Comment by enumag** [comment]
On the second line of the second image there is one more typo too. See https://github.com/07th-mod/watanagashi/issues/80.

**Comment by enumag** [comment]
Fixed now.
