### ISSUE TITLE
Missing Sprites Vol. 3

### ISSUE THREAD

**Issue by orian34** [07th-mod/tatarigoroshi#62]
Sprites : 
"portrait/normal/tie_2_"
"sprite/sunset/sa1b_warai_b1_"
"sprite/night/sa1a_warai_a1_"
"sprite/normal/sa5_hannbeso_a3_"
"sprite/normal/iri1_majime_"
"sprite/sunset/iri1_majime2_"
"sprite/sunset/iri2_majime_"
"sprite/sunset/me1a_majime_a1_"
"sprite/sunset/me1a_odoroki_a1_"
"sprite/sunset/me1a_tokui_a1_"
"sprite/sunset/me1a_wink_a1_"

Flashback : 
"flashback/g1"
"flashback/gr1"
"flashback/ma_s1"
"flashback/mati_o1"
"flashback/mo2"
"flashback/moon"
"flashback/ho1"
"flashback/hi1"
"flashback/ji1"
"flashback/ji2"
"flashback/simen3"
"flashback/damu4"
"flashback/je2"
"flashback/jd4"
"flashback/jt1"
"flashback/jy2"
"flashback/jsa1"
"flashback/gk1"
"flashback/gk3"
"flashback/furiker_a"
"sprite/flashback/sa1a_muhyou_a1_"
"sprite/flashback/sa1a_warai_a1_"
"sprite/flashback/sa1b_warai_b1_"
"sprite/flashback/tomi1_def_"
"sprite/flashback/sa1b_odoroki_b1_"
"sprite/flashback/sa1a_naku_a1_"
"sprite/flashback/me1a_warai_a1_"
"sprite/flashback/re1a_warai_a1_"
"sprite/flashback/re1b_warai_b1_"
"sprite/flashback/me1a_akuwarai_a1_"
"sprite/flashback/sa1a_hannbeso_a1_"
"sprite/flashback/re1b_kaii_b1_"

**Comment by enumag** [comment]
Oh great, more work. And we're not even done with wata.

**Comment by orian34** [comment]
pull request was sent

**Comment by orian34** [comment]
Can be closed now, I think.
