### ISSUE TITLE
Game stuck on title screen

### ISSUE THREAD

**Issue by Bashnet** [07th-mod/tatarigoroshi#66]
i installed the patch but the game seems to be stuck on the title screen. the menu options are not appearing. i checked if anyone had similar issues. i check the temp folder but i dint have a local.txt or an update.bat like you suggested for gagantous. i also installed the UI file you suggested for ryptahi, but it still didn't fix the issue.
<img width="686" alt="capture" src="https://user-images.githubusercontent.com/33022115/44091040-0f125c98-9fc4-11e8-9b01-e02aa9976362.PNG">

**Comment by ItaloKnox** [comment]
Yeah, the ``local`` and ``update`` files are not available anymore because we ran into an issue with TLS on Github, but we have something to fix that sometime soon. But anyway, that isn't necessary or anything, and it really looks like the UI is broken for you.

Can you install [this](http://07th-mod.com/rikachama/Tatarigoroshi-UI.7z) and see if it fixes the issue? In any case, inside your ``HigurashiEp03_Data`` folder there should be two ``sharedassets`` backup files if you used our installer to patch your game. If you restore them (just remove the ``.backup`` from the filename), it should boot the vanilla menus.

I'm going out right now so keep me updated. I'll check your issue by the time I get home.

**Comment by Bashnet** [comment]
i installed the files, still didint work. so i replaced the original files and the menu showed up


<img width="685" alt="capture" src="https://user-images.githubusercontent.com/33022115/44093160-98e56392-9fca-11e8-8059-53a8c523b13c.PNG">

**Comment by ItaloKnox** [comment]
That's odd. Just in case, is that the Steam version of the game?

**Comment by Bashnet** [comment]
no its the mangaGamer version

**Comment by enumag** [comment]
I assume you're playing with the original UI for now then? Can you re-create the error and then upload your output_log.txt?

Also did you get tatarigoroshi separately or in a pack purchase with all question arcs?

**Comment by ItaloKnox** [comment]
I see why the menus didn't work, then. If you still want to get the UI mod, [this one](http://07th-mod.com/rikachama/Tatarigoroshi-UI_MG.7z) should work.

By the way, did you install it manually or using or installer? If you got the wrong UI mod using the installer that means it was an issue in our side, I'll look into it if that was the case.

**Comment by Bashnet** [comment]
here's the txt file:
[output_log.txt](https://github.com/07th-mod/tatarigoroshi/files/2288732/output_log.txt)

**Comment by enumag** [comment]
As I thought you got the wrong version of the assets installed. Maybe our detection which one should be used is wrong? We can't do anything about it unless you answer the question from my previous comment:

"Also did you get tatarigoroshi separately or in a pack purchase with all question arcs?"

**Comment by ItaloKnox** [comment]
The detection should be fine, it's the same code since we introduced the UI mods. But we still need to know how the patch was installed, how it was bought and if my last suggestion worked or not.

**Comment by ghost** [comment]
We just got more information from two users with this issue @ItaloKnox .
One person had bought the question arcs pack from MangaGamer.
The other had bought standalone Tatari from GOG.
Both people resolved the problem by reverting to the vanilla UI.  I told them they can try manually installing http://07th-mod.com/rikachama/Tatarigoroshi-UI_MG.7z to see if that works - will update if I get any feedback.

**Comment by enumag** [comment]
I'll have completely new UI packs ready for the next release. Hopefully that might fix this.

**Comment by enumag** [comment]
Our last release and the UI hotfix we released today should fix the problem. Open a new issue if the problem persists.
