### ISSUE TITLE
Unity version mismatch for Mac/Linux DRM-free assets bundle

### ISSUE THREAD

**Issue by TellowKrinkle** [07th-mod/tatarigoroshi#67]
Game freezes with the error `Invalid serialized file version.  File: "<Long Path>/sharedassets0.assets" Expected version: 5.3.4p1. Actual version: 5.4.0f1.`

I noticed the Windows DRM-Free is 5.3.4p1 while the Mac/Linux one is 5.4.0f1

Here's the Mac GOG release's base files: 
[Tatari-UI_UNIX_MG_Orig.zip](https://github.com/07th-mod/tatarigoroshi/files/2333833/Tatari-UI_UNIX_MG_Orig.zip)

**Comment by enumag** [comment]
Yeah, 5.4.0f1 is the same version as on Steam so this should work: https://07th-mod.com/rikachama/Tatarigoroshi-UI_UNIX.7z

Can you test it?

**Comment by TellowKrinkle** [comment]
My game expects version `5.3.4p1`, but for some reason both of the unix ones are for `5.4.0f1` even though I assume the `-MG` one should have been `5.3.4p1`-based

(And yes, I did test it, it didn't work)

BTW if you open an assets file in a hex editor, the first readable thing is the version number so if you want to check what version an assets file is, you can look at that.

The closest one I have to working is the Windows DRM-Free one, which doesn't crash the game but causes the black and pink boxes normally associated with running a Windows assets file on non-windows.

**Comment by TellowKrinkle** [comment]
At least when I downloaded them, the assets file in https://07th-mod.com/rikachama/Tatarigoroshi-UI_UNIX.7z and https://07th-mod.com/rikachama/Tatarigoroshi-UI_UNIX-MG.7z are identical

**Comment by enumag** [comment]
Oh, ok. The UI is wrong. I'll generate new UI for the `5.3.4p1` version using your scripts and the vanilla version you provided.

**Comment by enumag** [comment]
Try this one: https://www.dropbox.com/s/2dzv1cm4bwbpn0e/tata-assets-mac-mg.7z?dl=0

**Comment by TellowKrinkle** [comment]
It appears to work

**Comment by enumag** [comment]
Nice. @ItaloKnox, can you replace `Tatarigoroshi-UI_UNIX-MG.7z` with the zip from my last link?

**Comment by ItaloKnox** [comment]
Of course, I'll take care of this later and close the issue afterward. Just got home and I'm honestly too tired to check the server.

**Comment by ItaloKnox** [comment]
Finished before than I thought. lol
