### ISSUE TITLE
Possible subject mixup

### ISSUE THREAD

**Issue by TellowKrinkle** [07th-mod/tatarigoroshi#68]
![image](https://user-images.githubusercontent.com/3315070/45471996-74a64b00-b6f8-11e8-9336-887f4ad9789a.png)
I think the line at the end of [this](https://github.com/07th-mod/tatarigoroshi/blob/1ab020ab5b6d8c06840e06cb05b469223de2190d/Update/tata_004.txt#L3616-L3623) should use `She` instead of `You`.  Does this seem right?

**Comment by orian34** [comment]
Maybe "I was told to" instead. Need a specialist on this

**Comment by enumag** [comment]
cc @Norgus @DoctorDiablo

**Comment by Norgus** [comment]
Agreed that it's "she" instead of "you".

**Comment by enumag** [comment]
Done. Thanks Norgus!
