### ISSUE TITLE
Pink text and missing menu

### ISSUE THREAD

**Issue by AbsolutelyDesignated** [07th-mod/tatarigoroshi#70]
I'm using the GOG version of Tatarigoroshi with the latest 07th Mod. I used the full installation, both graphics and voice. When I started the game, it presented me with this:
![The two text boxes](https://user-images.githubusercontent.com/48712781/54592665-b5ea2100-49e1-11e9-9130-8a4a59166468.png)
The top box is what I was presented with when I first started the game. The bottom box is what I got when I clicked once. Now, every other time this happened, I exited the game and restarted it. From there, I just got a blank black screen when it started up.
This time, however, I clicked the bottom(I think, it gives no feedback when i highlight one and it took a bit to  process it, at least from what i assume) option, and I got this:
![The title screen](https://user-images.githubusercontent.com/48712781/54592767-e5992900-49e1-11e9-9ed2-16c1e2b54121.png)
As you can see, it gives me no options and no way to do anything. Do you guys have any idea what's happening? I'm using Windows 10, but given that all the other chapters work, that shouldn't be a problem.

**Comment by ItaloKnox** [comment]
This is a known issue and we are already working on a fix. To get your game working, go into the ``HigurashiEp03_Data`` folder inside your installation folder and then delete the following files:

* ``sharedassets0.assets``
* ``sharedassets0.assets.resS``

After that, rename the backup back to the original names:

* ``sharedassets0.assets.backup`` to ``sharedassets0.assets`` 
* ``sharedassets0.assets.resS.backup`` to ``sharedassets0.assets.resS``

This will remove the UI mod but everything else should stay intact. I will update this thread with a working link for a new UI mod as soon as we get it fixed, then you can decide if you want to use it or keep the UI vanilla.

**Comment by enumag** [comment]
Wait what? Didn't we fix this recently?

**Comment by ItaloKnox** [comment]
Unless you deployed a second fix I'm pretty sure this is still happening.
What is the current engine version for all versions of the game? I have
this lingering feeling that we need three versions and I need to deploy
some new logic to the installer to make it work.

Em ter, 19 de mar de 2019 10:31, Jáchym Toušek <notifications@github.com>
escreveu:

**Comment by enumag** [comment]
> What is the current engine version for all versions of the game?

I don't know. There are too many different platforms to get the game from now. And I'm not even sure if the version is the same for all operating systems or not.

**Comment by ItaloKnox** [comment]
I guess we should collect some logs and see what we can do. Or maybe we can
postpone this a little and ask @drojf to implement the compilation during
installation. The web UI I'm working on should be done by the end of the
week, so there's a chance we'll be using the python installer as the
default soon enough.

Either way, I will take down the UI mod from the Tata installer. This
should give us time to look into this issue.

Em ter, 19 de mar de 2019 13:43, Jáchym Toušek <notifications@github.com>
escreveu:

**Comment by enumag** [comment]
Compilation during installation would require UABE which is windows only. I have no idea if it can run on wine.

**Comment by TellowKrinkle** [comment]
Just tested with the new python installer and it broke because we used the string `win` to represent Windows in the python files but `windows` in the JSON

With that fixed, it worked fine and I had no issues with my GOG Tatarigoroshi

**Comment by DuncanCasteleyn** [comment]
I also have this issue on Tatarigoroshi, all buttons and menus are pink, my cg is black

**Comment by enumag** [comment]
@DuncanCasteleyn 

Steam / MG / GOG?
Windows / Linux / Mac?
Can you upload the vanilla UI? It should be in the game directory (`sharedassets0.assets.backup` and `sharedassets0.assets.resS.backup`).

**Comment by DuncanCasteleyn** [comment]
Steam
Linux

Side note: the linux versions starting from chapter 3 is broken and crashes the entire linux desktop to get it working i'm forced to to use Proton version 3.16-4, which means i'm essentially using the windows version of the game, I was able to resolve the issue by installing the windows version of the UI. Maybe the orginal issue opener installed the UI for unix?

The installer seems to only have backed up the sharedassets0.assets.backup, the other one is gone.
[sharedassets0.assets.zip](https://github.com/07th-mod/tatarigoroshi/files/3090794/sharedassets0.assets.zip)

**Comment by ItaloKnox** [comment]
@enumag 

I used my server to grab the latest Linux version of the UI. [Here it is](http://172.110.6.39/ddl/Tata-UI_UNIX.7z).

**Comment by enumag** [comment]
@DuncanCasteleyn Can you reinstall the game to get me both of the files?

(The files Italo uploaded are for steam version, not GOG.)

**Comment by enumag** [comment]
Actually the file you sent seems to be Windows version. Not linux.

**Comment by enumag** [comment]
Try this. If it doesn't work then reinstall the game and send me the vanilla files.

https://www.dropbox.com/s/lytw78o8u26ouvm/Tatarigoroshi_steam_mac.7z?dl=0

**Comment by DuncanCasteleyn** [comment]
@enumag The game without patches is broken so I'm using Proton (which is based on Wine, see https://github.com/ValveSoftware/Proton/), since the Windows version is working i'm using Proton to play it with the patch which is working fine aside from some small bugs, not related to this patch.

**Comment by enumag** [comment]
In that case I'm guessing you actually need the windows version of the UI. Did you try that? Is it working?

**Comment by DuncanCasteleyn** [comment]
Like I said in a previous comment I'm using that version.

**Comment by enumag** [comment]
From your recent comments I have no idea if it's working or not and what you have and haven't tried...
So can we close this issue? If not, give me more details.

**Comment by DuncanCasteleyn** [comment]
https://github.com/07th-mod/tatarigoroshi/issues/70#issuecomment-484187101

**Comment by enumag** [comment]
Ah ok.
