### ISSUE TITLE
GOG version blank screen.

### ISSUE THREAD

**Issue by thewilder** [07th-mod/tatarigoroshi#71]
Hy there. After I installed every patch with the latest installer, I just get a blank screen upon launch. Any idea?

**Comment by enumag** [comment]
Can you share your output_log.txt? Should be in your game directory.

Most likely it's a bad unity version issue.

**Comment by thewilder** [comment]
Thanks for the fast reply. Here you go!

[output_log.txt](https://github.com/07th-mod/tatarigoroshi/files/3076172/output_log.txt)

**Comment by enumag** [comment]
Yeah... `Expected version: 5.4.0f1. Actual version: 5.3.4p1.`

Overwrite the existing UI files with these: https://07th-mod.com/rikachama/Tatarigoroshi-UI_MG.7z

@ItaloKnox Is the detection still broken for GOG?

**Comment by thewilder** [comment]
Actually, I did find those modified UI files and applied them earlier, but to no avail. It still won't start up.

**Comment by enumag** [comment]
Strange... can you send me the UI files from vanilla version? They should still be in the game directory, just renamed to `<original name>.backup`.

**Comment by thewilder** [comment]
Alright, just did a fresh install, same error. Also, I noticed that the installer for me always freezes when it tries to copy the intro movie.
[HigurashiEp03_Data.zip](https://github.com/07th-mod/tatarigoroshi/files/3076235/HigurashiEp03_Data.zip)

**Comment by enumag** [comment]
I think I sent you the wrong link earlier.

https://07th-mod.com/rikachama/Tatarigoroshi-UI.7z

**Comment by thewilder** [comment]
Thank you, that fixed it right away!

**Comment by enumag** [comment]
Good.

Note for us: GOG is using the same version as Steam but the installer does not recognize it correctly and instead installs the MG version. Most likely because GOG is DRM-free.

**Comment by ItaloKnox** [comment]
@thewilder Can you show me a picture of the game folder with .exe and all files visible? I will push a fix based on that.

**Comment by TellowKrinkle** [comment]
Ahh GOG must have finally gotten the music update, I'll check later
Other note: latest Python patcher chooses based on Unity version, not steaminess

**Comment by thewilder** [comment]
@ItaloKnox Here you go. Patcher kept freezing during unpacking the OP, so it couldn't delete the temp files.

![higurashi](https://user-images.githubusercontent.com/30772343/56087762-4e50b580-5e69-11e9-901e-02ce017ec78f.png)

**Comment by ItaloKnox** [comment]
Thanks. The Windows-only installer won't last much longer but [I pushed a band-aid fix for the issue](https://github.com/07th-mod/resources/commit/ca2bf08cc6fc119a1d13e61737adc02c0a31ccb9#diff-0e1d31f911f829c5458fcf54a854588e).
