### ISSUE TITLE
Cannot install patch due to Unity version mismatch

### ISSUE THREAD

**Issue by ghost** [07th-mod/tatarigoroshi#72]
The installer version is 0.0.6.9
The game is from Mangagamer, the Question Arc bundle
My OS is Windows 10 1903

The error message appears when I click 'Select Game Executable' and select the HigurashiEp03.exe file.

![Annotation 2019-08-08 161030](https://user-images.githubusercontent.com/53910579/62717674-9d1bef80-ba04-11e9-876e-fe857e257ab4.png)
[MOD-INSTALLER-LOG-2019-08-08_17-33-30.txt](https://github.com/07th-mod/tatarigoroshi/files/3482545/MOD-INSTALLER-LOG-2019-08-08_17-33-30.txt)

**Comment by enumag** [comment]
Fixed.
